#!/usr/bin/env python3
import os
import sys
import curses
import utils
from Menu import Menu
from MenuBar import MenuBar
from PlaylistMenu import PlaylistMenu, SongMenu


# cli commands


def help():
    print("help")

class MainMenu(object):

    def __init__(self, stdscreen):
        self.stdscreen = stdscreen
        self.stdscreen.addstr(0,0,"spotify-terminal",curses.A_NORMAL)
        self.menuBar = MenuBar()
        PlaylistMenu(self.stdscreen, self.menuBar).activate()

if __name__ == "__main__":
    # clears cache
    utils.clearCache()
    # inits config
    config = utils.readConfig()
    # spotify user long in if first time
    if not config.get("hasVerified", False):
        utils.verify()
    # displays playlist menu
    curses.wrapper(MainMenu)
    # kills threads and main program
    quit()
