
# remove ~/.config/spoti-cli/shortcuts.json to set the default to these values
defaultShortcuts = {
    "up": "k",
    "down": "j",
    "select": ["l", "KEY_ENTER"],
    "prevView": ["h", "KEY_ESCAPE"],
    "firstItem": "g",
    "lastItem": "G",
    "nextPage": "n",
    "prevPage": "N",
    "togglePlay": " ",
    "prevSong": "H",
    "nextSong": "L",
    "toggleShuffle": "s",
    "toggleRepeat": "r",
    "increaseVolume": "+",
    "decreaseVolume": "-",
    "addToQueue": "q",
    "goToAlbum": "A",
    "goToArtist": "a",
    "showLyrics": "i",
    "quit": "Q",
    "helpMenu": "?",
    "mainMenu": "m",
    "clearCache": "C",
    "toggleLog": "D",
}
